// Sample AI-generated summaries (markdown). Each maps WIPSONKEY → summary text.
// In production these would be generated by Claude Haiku from the PDF text and stored in DB.

const SUMMARY_KR_EUV = `## 발명의 명칭
EUV 노광공정용 펠리클 멤브레인 및 그 제조방법

## 기술 분야
본 발명은 극자외선(EUV) 리소그래피 공정에 사용되는 펠리클(pellicle) 멤브레인에 관한 것으로, 특히 7nm 이하 첨단 노드에서 마스크를 보호하면서도 EUV 광 투과율을 유지할 수 있는 박막 구조 및 그 제조방법을 제공한다.

## 해결 과제
- 기존 폴리실리콘 기반 펠리클은 EUV 광 흡수율이 높아 90% 이상의 투과율 확보가 어려움
- 13.5nm EUV에 노출 시 열적 안정성이 부족하여 막의 변형·파손 발생
- 멤브레인 두께가 30nm 이하로 얇아지면 기계적 강도가 급격히 저하

## 해결 수단
다공성 그래핀 적층 구조 위에 **수십 nm 두께의 보론 카바이드(B4C) 보호층**을 화학기상증착(CVD)으로 형성하여, 광 투과율 91% 이상을 유지하면서 인장강도를 1.2배 향상시킨다. 추가로 에지 영역에 몰리브덴 프레임을 통합하여 처짐을 방지한다.

## 핵심 구성요소
1. **다층 그래핀 코어** — 3~5층 적층, 두께 1.5~2.5nm
2. **B4C 보호층** — 양면 10nm씩, CVD로 형성
3. **몰리브덴 지지 프레임** — 둘레 폭 2mm
4. **반사 방지 코팅** — Ru 박막 0.5nm

## 차별점
- 기존 SK하이닉스 KR-10-2022-0078901은 단층 그래핀 + Si 보호층 구조 → 본 발명은 다층 그래핀 + B4C로 내열성을 250℃까지 확보
- ASML이 사용하는 다결정 실리콘 펠리클 대비 EUV 흡수율 30% 감소
- 청구항 1은 B4C 두께 비율(8~12nm)을 한정 → 회피 시 유의

## 적용 가능성
**개발 중인 EUV 마스크 보호 솔루션과 직접적 충돌 가능성 있음.** 특히 B4C 보호층의 두께 한정 사항은 당사 차세대 펠리클 설계와 겹치는 부분이 있으므로 회피 설계 또는 라이선싱 검토가 필요함.`;

const SUMMARY_US_INTEL = `## Title
High-k Dielectric Stack with Atomic Layer Deposited HfO2 for 3nm Nodes

## Technical Field
This invention relates to advanced gate dielectric stacks for sub-3nm FinFET and GAA transistors, focusing on **atomic layer deposition (ALD) of hafnium oxide** with engineered interface layers to suppress mobility degradation at ultra-thin equivalent oxide thickness (EOT).

## 해결 과제
- 1nm 이하 EOT 영역에서 SiO2 계면층(IL)이 전자 이동도를 30% 이상 저하시킴
- 일반 HfO2의 결정화 온도(~500℃)가 후공정 열적 예산을 초과
- 게이트 누설 전류와 신뢰성(BTI) 간 트레이드오프 존재

## 해결 수단
플라즈마 사전 처리로 0.5nm SiON 계면을 형성한 뒤, **순환 ALD(cyclic ALD)** 방식으로 HfO2와 Al2O3를 1:8 비율로 나노라미네이트(nanolaminate)하여 결정상을 비정질로 안정화한다. 후속 어닐링 온도를 400℃ 이하로 낮춰 후공정 호환성을 확보.

## 핵심 구성요소
1. **SiON 계면층** — 두께 0.5±0.1nm, 플라즈마 N2/O2 비율 조정
2. **HfO2/Al2O3 나노라미네이트** — 각 0.4nm, 8주기 반복
3. **TiN 메탈 게이트** — 5nm, 일함수 조정용 La 캡핑
4. **400℃ 저온 어닐링** — N2 분위기, 5분

## 차별점
- TSMC US-2023-0145672 대비 누설 전류 50% 감소
- 결정화 억제를 위해 Al2O3 캡핑을 사용한 점이 청구항 1의 핵심 한정 사항
- 어닐링 온도 400℃ 이하라는 점은 BEOL 호환성 확보의 결정적 차별점

## 적용 가능성
**3nm 이하 노드에서 게이트 절연막 후보로 검토 중인 기술과 부분적으로 중첩.** 단, 청구항이 ALD 사이클 비율(1:8)에 한정되어 있어 비율 조정을 통한 회피 설계 가능. 그러나 어닐링 온도 한정 사항은 광범위하게 적용될 수 있어 추가 분석 필요.`;

const SUMMARY_KR_BATTERY = `## 발명의 명칭
리튬 황 이차전지용 다공성 탄소-황 복합 전극재

## 기술 분야
본 발명은 차세대 고용량 리튬 황(Li-S) 이차전지의 양극재에 관한 것으로, 다공성 탄소 매트릭스에 황을 균일하게 담지하여 폴리설파이드 셔틀 현상을 억제하고 사이클 수명을 향상시킨 복합 전극재를 제공한다.

## 해결 과제
- 황 단독 사용 시 전기전도성이 낮아 율특성 저하 (~10-30 S/cm)
- 충방전 과정에서 발생하는 리튬 폴리설파이드(Li2Sx)가 전해액으로 용출되어 용량 감소
- 부피 팽창(~80%)으로 인한 전극 구조 붕괴

## 해결 수단
질소 도핑된 **계층형 다공성 탄소(NHPC)** 구조 내부에 황을 용융 함침법으로 도입하며, 마이크로-메소-매크로 다공성을 동시에 가져 폴리설파이드를 물리·화학적으로 흡착한다. 추가로 표면에 MoS2 양자점을 도입하여 변환반응 촉매로 작용시킨다.

## 핵심 구성요소
1. **N-도핑 계층형 탄소** — 비표면적 1,800 m²/g, 마이크로 30% / 메소 50% / 매크로 20%
2. **황 함량** — 70~75 wt%, 용융 함침 155℃ × 6시간
3. **MoS2 양자점 표면 코팅** — 평균 입자 3nm, 함량 2 wt%
4. **PVDF-HFP 바인더** — 5 wt%, NMP 슬러리

## 차별점
- 단순 메조포러스 탄소(Cabot CMK-3) 대비 폴리설파이드 흡착 능력 3배 향상
- MoS2 양자점 촉매 도입으로 충방전 효율(CE) 99.5% 달성
- 청구항 1은 비표면적(1,500 m²/g 이상)과 다공성 비율을 동시에 한정

## 적용 가능성
**리튬-황 전지 양극재 개발에 직접적 영향.** 다만 우리의 접근은 황화몰리브덴 대신 코발트 산화물 촉매를 사용 중이므로 청구항 1의 핵심 한정 사항(MoS2 양자점)에서는 회피 가능. 추가 검토 필요.`;

const SUMMARY_BIO = `## Title
Monoclonal Antibody Targeting PD-L1 with Enhanced Fc Effector Function

## 기술 분야
면역항암제 분야의 PD-L1 (Programmed Death-Ligand 1)을 표적으로 하는 단일클론항체에 관한 것으로, **Fc 영역의 글리코실레이션을 조작하여 ADCC(항체 의존성 세포 매개 세포독성) 효과를 강화**한 항체 의약품에 관한 발명이다.

## 해결 과제
- 기존 PD-L1 항체(Atezolizumab, Durvalumab)는 PD-1/PD-L1 경로 차단만 수행
- 종양 미세환경에서 항체-의존성 세포독성이 부족해 일부 환자에서 효능 제한
- Fc 영역 변형 시 면역원성 또는 안정성 저하 우려

## 해결 수단
중쇄 불변 영역의 **Asn297 부근 N-결합 글리코실레이션에서 푸코스(fucose)를 제거**한 비푸코실화(afucosylated) 항체 생성. NK세포의 FcγRIIIa(CD16a)와의 결합 친화도를 약 100배 향상시켜 ADCC 활성을 증대시키되, PD-L1 결합 친화도와 in vivo 반감기는 유지.

## 핵심 구성요소
1. **CDR 영역 서열** — HCDR1~3, LCDR1~3 (SEQ ID NO: 1~6)
2. **IgG1 Fc 골격** — Asn297 N-결합 글리칸, FUT8 KO 세포주(CHO-K1 derived)에서 발현
3. **푸코스 함량 5% 이하** — HPLC-MS로 분석
4. **PD-L1 결합 KD < 1nM** — SPR로 측정

## 차별점
- 표준 IgG1 대비 ADCC 100배 강화 (반면 보체 의존성 세포독성은 동일)
- 청구항 1은 푸코스 함량(5% 이하)과 PD-L1 결합 친화도(1nM 이하)를 동시 한정
- Atezolizumab(IgG1 결손형 N297A) 대비 NK 세포 매개 살해 효율 우수

## 적용 가능성
**현재 면역항암제 개발 방향과 직접적 관련 없음.** 우리 파이프라인은 PD-1 항체에 초점이 맞춰져 있고 PD-L1 비푸코실화 전략을 채택하지 않음. 무관 판정 가능하나, 향후 컴비네이션 요법 검토 시 라이선싱 대상으로 재검토 여지 있음.`;

window.SUMMARIES = {
  "KR-10-2023-0089421": SUMMARY_KR_EUV,
  "US-2024-0118233-A1": SUMMARY_US_INTEL,
  "KR-10-2024-0001523": SUMMARY_KR_BATTERY,
  "US-2024-0203456-A1": SUMMARY_BIO,
};

// For any patent without a hand-written summary, generate a reasonable placeholder
window.getSummary = function(patent) {
  if (window.SUMMARIES[patent.wipsonKey]) return window.SUMMARIES[patent.wipsonKey];
  return `## 발명의 명칭
${patent.fileTitle}

## 기술 분야
본 발명은 ${patent.classifier} 분야의 기술에 관한 것으로, 출원인(${patent.applicant})이 ${patent.appDate}에 출원한 ${patent.country === "KR" ? "국내" : "미국"} 특허이다.

## 해결 과제
- (AI 요약 생성 대기 중)
- 위 영역은 변리사 프롬프트에 따라 자동 생성됩니다.
- 일반적으로 3~5개의 핵심 문제점이 bullet으로 나열됩니다.

## 해결 수단
구체적인 해결 방법이 마크다운 본문으로 정리됩니다. **굵은 글씨**, *기울임*, \`코드\` 같은 인라인 강조도 그대로 렌더링됩니다.

## 핵심 구성요소
1. 첫 번째 핵심 구성요소
2. 두 번째 핵심 구성요소
3. 세 번째 핵심 구성요소

## 차별점
선행 특허와의 차별점을 정리합니다. WIPSONKEY 참조도 가능합니다.

## 적용 가능성
**검토 의견:** 이 영역은 변리사 프롬프트에 따라 "개발 중인 기술과의 직접적 관련성"을 판단하는 핵심 의견을 담습니다.`;
};
